// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.huangsuip.netty.protobuf;

public final class HeaderProto {
  private HeaderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     */
    int getCode();

    /**
     * <pre>
     *消息长度
     * </pre>
     *
     * <code>int32 length = 2;</code>
     */
    int getLength();

    /**
     * <code>int64 sessionId = 3;</code>
     */
    long getSessionId();

    /**
     * <pre>
     *消息类型代码
     * </pre>
     *
     * <code>.MessageType type = 4;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     *消息类型代码
     * </pre>
     *
     * <code>.MessageType type = 4;</code>
     */
    com.huangsuip.netty.protobuf.MessageTypeProto.MessageType getType();

    /**
     * <pre>
     *消息优先级
     * </pre>
     *
     * <code>int32 priority = 5;</code>
     */
    int getPriority();

    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */
    int getAttachmentCount();
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */
    boolean containsAttachment(
        java.lang.String key);
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getAttachment();
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Any>
    getAttachmentMap();
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */

    com.google.protobuf.Any getAttachmentOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue);
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */

    com.google.protobuf.Any getAttachmentOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 16: {

              length_ = input.readInt32();
              break;
            }
            case 24: {

              sessionId_ = input.readInt64();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 40: {

              priority_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                attachment_ = com.google.protobuf.MapField.newMapField(
                    AttachmentDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
              attachment__ = input.readMessage(
                  AttachmentDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              attachment_.getMutableMap().put(
                  attachment__.getKey(), attachment__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.huangsuip.netty.protobuf.HeaderProto.internal_static_Header_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 6:
          return internalGetAttachment();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.huangsuip.netty.protobuf.HeaderProto.internal_static_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.huangsuip.netty.protobuf.HeaderProto.Header.class, com.huangsuip.netty.protobuf.HeaderProto.Header.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    /**
     * <pre>
     *消息长度
     * </pre>
     *
     * <code>int32 length = 2;</code>
     */
    public int getLength() {
      return length_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionId_;
    /**
     * <code>int64 sessionId = 3;</code>
     */
    public long getSessionId() {
      return sessionId_;
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     *消息类型代码
     * </pre>
     *
     * <code>.MessageType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     *消息类型代码
     * </pre>
     *
     * <code>.MessageType type = 4;</code>
     */
    public com.huangsuip.netty.protobuf.MessageTypeProto.MessageType getType() {
      @SuppressWarnings("deprecation")
      com.huangsuip.netty.protobuf.MessageTypeProto.MessageType result = com.huangsuip.netty.protobuf.MessageTypeProto.MessageType.valueOf(type_);
      return result == null ? com.huangsuip.netty.protobuf.MessageTypeProto.MessageType.UNRECOGNIZED : result;
    }

    public static final int PRIORITY_FIELD_NUMBER = 5;
    private int priority_;
    /**
     * <pre>
     *消息优先级
     * </pre>
     *
     * <code>int32 priority = 5;</code>
     */
    public int getPriority() {
      return priority_;
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 6;
    private static final class AttachmentDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Any> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Any>newDefaultInstance(
                  com.huangsuip.netty.protobuf.HeaderProto.internal_static_Header_AttachmentEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Any.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Any> attachment_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
    internalGetAttachment() {
      if (attachment_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AttachmentDefaultEntryHolder.defaultEntry);
      }
      return attachment_;
    }

    public int getAttachmentCount() {
      return internalGetAttachment().getMap().size();
    }
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */

    public boolean containsAttachment(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAttachment().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAttachmentMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Any> getAttachment() {
      return getAttachmentMap();
    }
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.Any> getAttachmentMap() {
      return internalGetAttachment().getMap();
    }
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */

    public com.google.protobuf.Any getAttachmentOrDefault(
        java.lang.String key,
        com.google.protobuf.Any defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetAttachment().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *附加属性
     * </pre>
     *
     * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
     */

    public com.google.protobuf.Any getAttachmentOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Any> map =
          internalGetAttachment().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (length_ != 0) {
        output.writeInt32(2, length_);
      }
      if (sessionId_ != 0L) {
        output.writeInt64(3, sessionId_);
      }
      if (type_ != com.huangsuip.netty.protobuf.MessageTypeProto.MessageType.SERVICE_REQ.getNumber()) {
        output.writeEnum(4, type_);
      }
      if (priority_ != 0) {
        output.writeInt32(5, priority_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetAttachment(),
          AttachmentDefaultEntryHolder.defaultEntry,
          6);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (length_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, length_);
      }
      if (sessionId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionId_);
      }
      if (type_ != com.huangsuip.netty.protobuf.MessageTypeProto.MessageType.SERVICE_REQ.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, type_);
      }
      if (priority_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, priority_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Any> entry
           : internalGetAttachment().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Any>
        attachment__ = AttachmentDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(6, attachment__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.huangsuip.netty.protobuf.HeaderProto.Header)) {
        return super.equals(obj);
      }
      com.huangsuip.netty.protobuf.HeaderProto.Header other = (com.huangsuip.netty.protobuf.HeaderProto.Header) obj;

      if (getCode()
          != other.getCode()) return false;
      if (getLength()
          != other.getLength()) return false;
      if (getSessionId()
          != other.getSessionId()) return false;
      if (type_ != other.type_) return false;
      if (getPriority()
          != other.getPriority()) return false;
      if (!internalGetAttachment().equals(
          other.internalGetAttachment())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getLength();
      hash = (37 * hash) + SESSIONID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSessionId());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority();
      if (!internalGetAttachment().getMap().isEmpty()) {
        hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAttachment().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.huangsuip.netty.protobuf.HeaderProto.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.huangsuip.netty.protobuf.HeaderProto.Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Header)
        com.huangsuip.netty.protobuf.HeaderProto.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.huangsuip.netty.protobuf.HeaderProto.internal_static_Header_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 6:
            return internalGetMutableAttachment();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.huangsuip.netty.protobuf.HeaderProto.internal_static_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.huangsuip.netty.protobuf.HeaderProto.Header.class, com.huangsuip.netty.protobuf.HeaderProto.Header.Builder.class);
      }

      // Construct using com.huangsuip.netty.protobuf.HeaderProto.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        length_ = 0;

        sessionId_ = 0L;

        type_ = 0;

        priority_ = 0;

        internalGetMutableAttachment().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.huangsuip.netty.protobuf.HeaderProto.internal_static_Header_descriptor;
      }

      @java.lang.Override
      public com.huangsuip.netty.protobuf.HeaderProto.Header getDefaultInstanceForType() {
        return com.huangsuip.netty.protobuf.HeaderProto.Header.getDefaultInstance();
      }

      @java.lang.Override
      public com.huangsuip.netty.protobuf.HeaderProto.Header build() {
        com.huangsuip.netty.protobuf.HeaderProto.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.huangsuip.netty.protobuf.HeaderProto.Header buildPartial() {
        com.huangsuip.netty.protobuf.HeaderProto.Header result = new com.huangsuip.netty.protobuf.HeaderProto.Header(this);
        int from_bitField0_ = bitField0_;
        result.code_ = code_;
        result.length_ = length_;
        result.sessionId_ = sessionId_;
        result.type_ = type_;
        result.priority_ = priority_;
        result.attachment_ = internalGetAttachment();
        result.attachment_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.huangsuip.netty.protobuf.HeaderProto.Header) {
          return mergeFrom((com.huangsuip.netty.protobuf.HeaderProto.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.huangsuip.netty.protobuf.HeaderProto.Header other) {
        if (other == com.huangsuip.netty.protobuf.HeaderProto.Header.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getLength() != 0) {
          setLength(other.getLength());
        }
        if (other.getSessionId() != 0L) {
          setSessionId(other.getSessionId());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getPriority() != 0) {
          setPriority(other.getPriority());
        }
        internalGetMutableAttachment().mergeFrom(
            other.internalGetAttachment());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.huangsuip.netty.protobuf.HeaderProto.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.huangsuip.netty.protobuf.HeaderProto.Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private int length_ ;
      /**
       * <pre>
       *消息长度
       * </pre>
       *
       * <code>int32 length = 2;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <pre>
       *消息长度
       * </pre>
       *
       * <code>int32 length = 2;</code>
       */
      public Builder setLength(int value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息长度
       * </pre>
       *
       * <code>int32 length = 2;</code>
       */
      public Builder clearLength() {
        
        length_ = 0;
        onChanged();
        return this;
      }

      private long sessionId_ ;
      /**
       * <code>int64 sessionId = 3;</code>
       */
      public long getSessionId() {
        return sessionId_;
      }
      /**
       * <code>int64 sessionId = 3;</code>
       */
      public Builder setSessionId(long value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0L;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       *消息类型代码
       * </pre>
       *
       * <code>.MessageType type = 4;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       *消息类型代码
       * </pre>
       *
       * <code>.MessageType type = 4;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型代码
       * </pre>
       *
       * <code>.MessageType type = 4;</code>
       */
      public com.huangsuip.netty.protobuf.MessageTypeProto.MessageType getType() {
        @SuppressWarnings("deprecation")
        com.huangsuip.netty.protobuf.MessageTypeProto.MessageType result = com.huangsuip.netty.protobuf.MessageTypeProto.MessageType.valueOf(type_);
        return result == null ? com.huangsuip.netty.protobuf.MessageTypeProto.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *消息类型代码
       * </pre>
       *
       * <code>.MessageType type = 4;</code>
       */
      public Builder setType(com.huangsuip.netty.protobuf.MessageTypeProto.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息类型代码
       * </pre>
       *
       * <code>.MessageType type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <pre>
       *消息优先级
       * </pre>
       *
       * <code>int32 priority = 5;</code>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <pre>
       *消息优先级
       * </pre>
       *
       * <code>int32 priority = 5;</code>
       */
      public Builder setPriority(int value) {
        
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息优先级
       * </pre>
       *
       * <code>int32 priority = 5;</code>
       */
      public Builder clearPriority() {
        
        priority_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Any> attachment_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetAttachment() {
        if (attachment_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        return attachment_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Any>
      internalGetMutableAttachment() {
        onChanged();;
        if (attachment_ == null) {
          attachment_ = com.google.protobuf.MapField.newMapField(
              AttachmentDefaultEntryHolder.defaultEntry);
        }
        if (!attachment_.isMutable()) {
          attachment_ = attachment_.copy();
        }
        return attachment_;
      }

      public int getAttachmentCount() {
        return internalGetAttachment().getMap().size();
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      public boolean containsAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetAttachment().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAttachmentMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any> getAttachment() {
        return getAttachmentMap();
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      public java.util.Map<java.lang.String, com.google.protobuf.Any> getAttachmentMap() {
        return internalGetAttachment().getMap();
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      public com.google.protobuf.Any getAttachmentOrDefault(
          java.lang.String key,
          com.google.protobuf.Any defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetAttachment().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      public com.google.protobuf.Any getAttachmentOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Any> map =
            internalGetAttachment().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearAttachment() {
        internalGetMutableAttachment().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      public Builder removeAttachment(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Any>
      getMutableAttachment() {
        return internalGetMutableAttachment().getMutableMap();
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */
      public Builder putAttachment(
          java.lang.String key,
          com.google.protobuf.Any value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableAttachment().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *附加属性
       * </pre>
       *
       * <code>map&lt;string, .google.protobuf.Any&gt; attachment = 6;</code>
       */

      public Builder putAllAttachment(
          java.util.Map<java.lang.String, com.google.protobuf.Any> values) {
        internalGetMutableAttachment().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Header)
    }

    // @@protoc_insertion_point(class_scope:Header)
    private static final com.huangsuip.netty.protobuf.HeaderProto.Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.huangsuip.netty.protobuf.HeaderProto.Header();
    }

    public static com.huangsuip.netty.protobuf.HeaderProto.Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @java.lang.Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.huangsuip.netty.protobuf.HeaderProto.Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_AttachmentEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Header_AttachmentEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014header.proto\032\031google/protobuf/any.prot" +
      "o\032\022message_type.proto\"\335\001\n\006Header\022\014\n\004code" +
      "\030\001 \001(\005\022\016\n\006length\030\002 \001(\005\022\021\n\tsessionId\030\003 \001(" +
      "\003\022\032\n\004type\030\004 \001(\0162\014.MessageType\022\020\n\010priorit" +
      "y\030\005 \001(\005\022+\n\nattachment\030\006 \003(\0132\027.Header.Att" +
      "achmentEntry\032G\n\017AttachmentEntry\022\013\n\003key\030\001" +
      " \001(\t\022#\n\005value\030\002 \001(\0132\024.google.protobuf.An" +
      "y:\0028\001B+\n\034com.huangsuip.netty.protobufB\013H" +
      "eaderProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.huangsuip.netty.protobuf.MessageTypeProto.getDescriptor(),
        });
    internal_static_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_descriptor,
        new java.lang.String[] { "Code", "Length", "SessionId", "Type", "Priority", "Attachment", });
    internal_static_Header_AttachmentEntry_descriptor =
      internal_static_Header_descriptor.getNestedTypes().get(0);
    internal_static_Header_AttachmentEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Header_AttachmentEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.huangsuip.netty.protobuf.MessageTypeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
