// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message_type.proto

package com.huangsuip.netty.protobuf;

public final class MessageTypeProto {
  private MessageTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SERVICE_REQ = 0;</code>
     */
    SERVICE_REQ(0),
    /**
     * <code>SERVICE_RESP = 1;</code>
     */
    SERVICE_RESP(1),
    /**
     * <code>ONE_WAY = 2;</code>
     */
    ONE_WAY(2),
    /**
     * <code>LOGIN_REQ = 3;</code>
     */
    LOGIN_REQ(3),
    /**
     * <code>LOGIN_RESP = 4;</code>
     */
    LOGIN_RESP(4),
    /**
     * <code>HEARTBEAT_REQ = 5;</code>
     */
    HEARTBEAT_REQ(5),
    /**
     * <code>HEARTBEAT_RESP = 6;</code>
     */
    HEARTBEAT_RESP(6),
    /**
     * <code>TEST_CMD = 7;</code>
     */
    TEST_CMD(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SERVICE_REQ = 0;</code>
     */
    public static final int SERVICE_REQ_VALUE = 0;
    /**
     * <code>SERVICE_RESP = 1;</code>
     */
    public static final int SERVICE_RESP_VALUE = 1;
    /**
     * <code>ONE_WAY = 2;</code>
     */
    public static final int ONE_WAY_VALUE = 2;
    /**
     * <code>LOGIN_REQ = 3;</code>
     */
    public static final int LOGIN_REQ_VALUE = 3;
    /**
     * <code>LOGIN_RESP = 4;</code>
     */
    public static final int LOGIN_RESP_VALUE = 4;
    /**
     * <code>HEARTBEAT_REQ = 5;</code>
     */
    public static final int HEARTBEAT_REQ_VALUE = 5;
    /**
     * <code>HEARTBEAT_RESP = 6;</code>
     */
    public static final int HEARTBEAT_RESP_VALUE = 6;
    /**
     * <code>TEST_CMD = 7;</code>
     */
    public static final int TEST_CMD_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return SERVICE_REQ;
        case 1: return SERVICE_RESP;
        case 2: return ONE_WAY;
        case 3: return LOGIN_REQ;
        case 4: return LOGIN_RESP;
        case 5: return HEARTBEAT_REQ;
        case 6: return HEARTBEAT_RESP;
        case 7: return TEST_CMD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.huangsuip.netty.protobuf.MessageTypeProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MessageType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022message_type.proto*\221\001\n\013MessageType\022\017\n\013" +
      "SERVICE_REQ\020\000\022\020\n\014SERVICE_RESP\020\001\022\013\n\007ONE_W" +
      "AY\020\002\022\r\n\tLOGIN_REQ\020\003\022\016\n\nLOGIN_RESP\020\004\022\021\n\rH" +
      "EARTBEAT_REQ\020\005\022\022\n\016HEARTBEAT_RESP\020\006\022\014\n\010TE" +
      "ST_CMD\020\007B0\n\034com.huangsuip.netty.protobuf" +
      "B\020MessageTypeProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
